baseURL = "http://example.org/"
languageCode = "en-us"
title = "NUS Computing"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "coderzh"

[Params]
  AuthorHomepage = "http://blog.coderzh.com"
  BottomIntroduce = "Introduce1 <br/> Introduce2"
  Description = ""
  Subtitle = "Website for SoC Students"
  Twitter = "coderzh"
  GitHub = "coderzh"
  Facebook = "coderzh"
  LinkIn = "coderzh"
  Imglogo = "logo.png"
  AuthorImg = "img/author.jpg"
  DateFormat = "2006/01/02/"
  MonthFormat = "2006/01"
  FancyBox = true
  # DuoShuoShortName = "coderzh"
  DisqusShortName = "coderzh"
  GoogleAnalyticsID = "UA-10147768-2"
  headerImage = "cover-home.jpg"

  [Params.Strings]
    Search = "Search"
    PageNotFound = "The page you visit does not exist"
    ShowSideBar = "Show sidebar"
    HideSideBar = "Hide sidebar"
    Categories = "Categories"
    Archive = "Archive"
    Tags = "Tags"
    TagCloud = "Tag Cloud"
    Rss = "RSS Subscription"
    TableOfContents = "Table of Contents"

[Menu]
  [[Menu.Main]]
    Name = "Home"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "About"
    URL = "/about"
    Weight = 2
  [[Menu.Main]]
    Name = "Events"
    URL = "/events"
    Weight = 3
  [[Menu.Main]]
    Name = "Connect"
    URL = "/connect"
    Weight = 4
